definitions:
  domain.ClassicPlacesSettings:
    properties:
      location:
        $ref: '#/definitions/domain.Coordinate'
      priceAvg:
        type: integer
      recommendation:
        $ref: '#/definitions/domain.RecommendationOpts'
      tags:
        items:
          type: integer
        type: array
    type: object
  domain.Collection:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      order:
        type: integer
      places:
        items:
          $ref: '#/definitions/domain.Place'
        type: array
      updatedAt:
        type: string
      visible:
        type: boolean
    type: object
  domain.CollectionPlacesSettings:
    properties:
      collectionId:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
    type: object
  domain.CollectionPreview:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      order:
        type: integer
      updatedAt:
        type: string
      visible:
        type: boolean
    type: object
  domain.Coordinate:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
  domain.Lobby:
    properties:
      createdAt:
        type: string
      id:
        type: string
      places:
        items:
          $ref: '#/definitions/domain.Place'
        type: array
      settings:
        $ref: '#/definitions/domain.LobbySettings'
      state:
        type: string
      swipes:
        items:
          $ref: '#/definitions/domain.Swipe'
        type: array
      type:
        type: string
      users:
        items:
          $ref: '#/definitions/domain.User'
        type: array
    type: object
  domain.LobbySettings:
    properties:
      classicPlaces:
        $ref: '#/definitions/domain.ClassicPlacesSettings'
      collectionPlaces:
        $ref: '#/definitions/domain.CollectionPlacesSettings'
      type:
        type: string
    type: object
  domain.Place:
    properties:
      address:
        type: string
      boost:
        type: number
      boostRadius:
        type: number
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      location:
        $ref: '#/definitions/domain.Coordinate'
      priceAvg:
        type: integer
      reviewCount:
        type: integer
      reviewRating:
        type: number
      shortDescription:
        type: string
      source:
        type: string
      tags:
        items:
          $ref: '#/definitions/domain.Tag'
        type: array
      title:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  domain.RecommendationOpts:
    properties:
      classic:
        $ref: '#/definitions/domain.RecommendationOptsClassic'
      type:
        $ref: '#/definitions/domain.RecommendationType'
    type: object
  domain.RecommendationOptsClassic:
    properties:
      distBound:
        type: integer
      distCoeff:
        type: number
      distPower:
        type: number
      priceBound:
        type: integer
      priceCoeff:
        type: number
      pricePower:
        type: number
    type: object
  domain.RecommendationType:
    enum:
    - classic
    type: string
    x-enum-varnames:
    - RecommendationTypeClassic
  domain.Swipe:
    properties:
      cardID:
        type: integer
      id:
        type: integer
      lobbyID:
        type: string
      type:
        type: string
      userID:
        type: string
    type: object
  domain.Tag:
    properties:
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      order:
        type: integer
      visible:
        type: boolean
    type: object
  domain.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      telegram:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: Manage cards, lobbies, swipes
  title: DishDash server
  version: "2.0"
paths:
  /collections:
    get:
      consumes:
      - application/json
      description: Get a list of collections from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of collections
          schema:
            items:
              $ref: '#/definitions/domain.Collection'
            type: array
        "500":
          description: Internal Server Error
      summary: Get collections
      tags:
      - collections
  /collections/{id}:
    get:
      consumes:
      - application/json
      description: Get a collection with same id from database
      parameters:
      - description: Collection ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Collection
          schema:
            $ref: '#/definitions/domain.Collection'
        "500":
          description: Internal Server Error
      summary: Get a collection
      tags:
      - collections
  /collections/preview:
    get:
      consumes:
      - application/json
      description: Get a list of collections preveiws from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of collections previews
          schema:
            items:
              $ref: '#/definitions/domain.CollectionPreview'
            type: array
        "500":
          description: Internal Server Error
      summary: Get collections previews
      tags:
      - collections
  /collections/preview/{id}:
    get:
      consumes:
      - application/json
      description: Get a collection preview with same id from database
      parameters:
      - description: Collection ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Collection
          schema:
            $ref: '#/definitions/domain.CollectionPreview'
        "500":
          description: Internal Server Error
      summary: Get a collection preview
      tags:
      - collections
  /lobbies:
    post:
      consumes:
      - application/json
      description: Create a new lobby in the database with given settings
      parameters:
      - description: lobby settings
        in: body
        name: lobby
        required: true
        schema:
          $ref: '#/definitions/domain.LobbySettings'
      produces:
      - application/json
      responses:
        "200":
          description: Saved lobby
          schema:
            $ref: '#/definitions/domain.Lobby'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a lobby with given settings
      tags:
      - lobbies
  /lobbies/{id}:
    get:
      consumes:
      - application/json
      description: Get a lobby from the database by ID
      parameters:
      - description: lobby ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: lobby data
          schema:
            $ref: '#/definitions/domain.Lobby'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get lobby by ID
      tags:
      - lobbies
  /places/tag:
    get:
      consumes:
      - application/json
      description: Get a list of tags from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of tags
          schema:
            items:
              $ref: '#/definitions/domain.Tag'
            type: array
        "500":
          description: Internal Server Error
      summary: Get tags
      tags:
      - places
  /users:
    post:
      consumes:
      - application/json
      description: Save a new user in the database
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: Saved user
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Save a user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user in the database
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update a user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user from the database by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user by ID
      tags:
      - users
  /users/telegram/{telegram}:
    get:
      consumes:
      - application/json
      description: Get a user from the database by Telegram number
      parameters:
      - description: Telegram number
        in: path
        name: telegram
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user by Telegram
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Token
    type: apiKey
swagger: "2.0"
