version: "3.8"

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    restart: unless-stopped
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-backend.entrypoints=https"
      - "traefik.http.routers.go-backend.rule=Host(`dishdash.ru`) && (PathPrefix(`/api`) || Path(`/socket.io/`))"
      - "traefik.http.routers.go-backend.tls.certresolver=le"
      - "traefik.http.services.go-backend.loadbalancer.server.port=80"
    networks:
      - proxynet
      - database

networks:
  proxynet:
    name: proxynet
    external: true
  database:
    name: database
    external: true
