// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cards": {
            "get": {
                "description": "Get a list of cards from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get cards",
                "responses": {
                    "200": {
                        "description": "List of cards",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/card.cardOutput"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new card in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Create a card",
                "parameters": [
                    {
                        "description": "Card data",
                        "name": "card",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.CardInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Saved card",
                        "schema": {
                            "$ref": "#/definitions/card.cardOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/cards/tags": {
            "get": {
                "description": "Get a list of tags from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get tags",
                "responses": {
                    "200": {
                        "description": "List of tags",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/card.tagOutput"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new tag in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Create a tag",
                "parameters": [
                    {
                        "description": "Tag data",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.TagInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Saved tag",
                        "schema": {
                            "$ref": "#/definitions/card.tagOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/lobbies": {
            "post": {
                "description": "Create a new lobby in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "Create a lobby",
                "parameters": [
                    {
                        "description": "Lobby data",
                        "name": "lobby",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.LobbyInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Saved lobby",
                        "schema": {
                            "$ref": "#/definitions/lobby.lobbyOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/lobbies/find": {
            "post": {
                "description": "shortcut for find nearest + create if not close enough",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "find lobby",
                "parameters": [
                    {
                        "description": "Location + Distance (in metres)",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/lobby.findLobbyInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lobby.lobbyOutput"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/lobby.lobbyOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/lobbies/nearest": {
            "post": {
                "description": "find nearest lobby in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "find nearest lobby",
                "parameters": [
                    {
                        "description": "Location",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Coordinate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nearest Lobby + Distance (in metres)",
                        "schema": {
                            "$ref": "#/definitions/lobby.nearestLobbyOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/lobbies/{id}": {
            "get": {
                "description": "Get a lobby from the database by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "Get lobby by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lobby data",
                        "schema": {
                            "$ref": "#/definitions/lobby.lobbyOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "delete a lobby in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "delete a lobby",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get a list of users from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get users",
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.userOutput"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update a existing user in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.UserInputExtended"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "$ref": "#/definitions/user.userOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new user in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Saved user",
                        "schema": {
                            "$ref": "#/definitions/user.userOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get a user from the database by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User data",
                        "schema": {
                            "$ref": "#/definitions/user.userOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "card.cardOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                },
                "priceMax": {
                    "type": "integer"
                },
                "priceMin": {
                    "type": "integer"
                },
                "shortDescription": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/card.tagOutput"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "card.tagOutput": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Coordinate": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "lobby.cardOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                },
                "priceMax": {
                    "type": "integer"
                },
                "priceMin": {
                    "type": "integer"
                },
                "shortDescription": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "lobby.finalVoteOutput": {
            "type": "object",
            "properties": {
                "cardID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lobbyID": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "lobby.findLobbyInput": {
            "type": "object",
            "properties": {
                "dist": {
                    "type": "number"
                },
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                }
            }
        },
        "lobby.lobbyOutput": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobby.cardOutput"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "finalVotes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobby.finalVoteOutput"
                    }
                },
                "id": {
                    "type": "string"
                },
                "lobbySettings": {
                    "$ref": "#/definitions/lobby.lobbySettingsOutput"
                },
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                },
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobby.matchOutput"
                    }
                },
                "swipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobby.swipeOutput"
                    }
                }
            }
        },
        "lobby.lobbySettingsOutput": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "maxDistance": {
                    "type": "number"
                },
                "priceMax": {
                    "type": "integer"
                },
                "priceMin": {
                    "type": "integer"
                }
            }
        },
        "lobby.matchOutput": {
            "type": "object",
            "properties": {
                "cardID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lobbyID": {
                    "type": "string"
                }
            }
        },
        "lobby.nearestLobbyOutput": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "lobby": {
                    "$ref": "#/definitions/lobby.lobbyOutput"
                }
            }
        },
        "lobby.swipeOutput": {
            "type": "object",
            "properties": {
                "cardID": {
                    "type": "integer"
                },
                "lobbyID": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "usecase.CardInput": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                },
                "priceMax": {
                    "type": "integer"
                },
                "priceMin": {
                    "type": "integer"
                },
                "shortDescription": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "usecase.LobbyInput": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/domain.Coordinate"
                }
            }
        },
        "usecase.TagInput": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "usecase.UserInput": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "usecase.UserInputExtended": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.userOutput": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DishDash server",
	Description:      "Manage cards, lobbies, swipes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
