name: CD Prod

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Write tag for deploy
        required: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Fail if branch is not main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered on a branch other than main"
          exit 1

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dishdash-miniapp:latest
            ${{ secrets.DOCKER_USERNAME }}/dishdash-backend:${{ env.COMMIT_SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/dishdash-miniapp:${{ github.event.inputs.tag_name }}

      - name: Trigger Watchtower to update dev container
        shell: bash
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}" ${{ secrets.WATCHTOWER_UPDATE_ENDPOINT_DEV }}
